version: '3.8'

services:
  # url-shortener:
  #   build: ./
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_PORT=6379
  #     - DB_PASSWORD=""
  #     - DB_HOST=db
  #     - SERVER_PORT=8000
  #     - DOMAIN=localhost:8000
  db:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  redis_data: